//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtectedConfigCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class SavedSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SavedSettings defaultInstance = ((SavedSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SavedSettings())));
        
        public static SavedSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnterprisePath {
            get {
                return ((string)(this["EnterprisePath"]));
            }
            set {
                this["EnterprisePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CfFileDir {
            get {
                return ((string)(this["CfFileDir"]));
            }
            set {
                this["CfFileDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EpfSrcDir {
            get {
                return ((string)(this["EpfSrcDir"]));
            }
            set {
                this["EpfSrcDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string V8UnpackPath {
            get {
                return ((string)(this["V8UnpackPath"]));
            }
            set {
                this["V8UnpackPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EpfFileDir {
            get {
                return ((string)(this["EpfFileDir"]));
            }
            set {
                this["EpfFileDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModuleNames {
            get {
                return ((string)(this["ModuleNames"]));
            }
            set {
                this["ModuleNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LicenceEditDir {
            get {
                return ((string)(this["LicenceEditDir"]));
            }
            set {
                this["LicenceEditDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBaseSettings {
            get {
                return ((string)(this["DBaseSettings"]));
            }
            set {
                this["DBaseSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBaseProtectedSettings {
            get {
                return ((string)(this["DBaseProtectedSettings"]));
            }
            set {
                this["DBaseProtectedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeySeries {
            get {
                return ((string)(this["KeySeries"]));
            }
            set {
                this["KeySeries"] = value;
            }
        }
    }
}
